<?php

return [
    'page_order' => [
        'landing',
        'about-slide',
        'stack-skill-slide',
        'project-slide',
        'reference-slide',
        'contact-slide',
    ],
    'skills' => [
        'PHP',
        'Laravel',
        'React',
        'JavaScript',
        'jQuery',
        'Twig',
        'HTML',
        'CSS',
        'Sass',
        'Less',
        'Wordpress',
        'Plugin WP',
        'Temi WP',
        'MySQL',
        'Node.js',
        'Tailwind CSS',
        'Markdown',
        'DB design',
        'Software Design',
        'Photoshop',
        'Illustrator',
        'OOP',
        'Object Oriented Programming',
        'Ottimizzazione SEO',
        'SEO onsite',
        'MVC',
        'Eloquent ORM',
        'Database Relazionali',
        'Scalabilità',
        'API RESTful',
        'API SOAP',
        'NPM',
        'CRUD',
        'Indicizzazione',
        'CBP',
        'Content Based Programming',
        'SPA',
        'Single Page Application',
        'Fluid UI/UX',
        'DOM',
        'Automazione',
        'Utility',
        'Responsive',
        'Nesting',
        'Riusabilità',
        'Audit Qualità',
        'Autid SEO',
        'Audit Software',
        'Layout Building',
        'Layout Design',
        'Documentazioni tecniche',
        'Gestione Contenuti',
        'Normalizzazione DB',
        'Diagrammi ER',
        'Principi SOLID',
        'Pattern architetturali',
        'Documentazione e UML',
        'Progettazione componenti',
        'Vettorializzazione',
        'Esportazione per Web',
        'Ottimizzazione Storage',
    ],
    'random_phrases' => [
        'sono interessato ai progetti',
        'non sono un bot',
        'sono in buona fede',
        'mi interessano i progetti',
        'vorrei sapere di più',
        'non sono una intelligenza artificiale',
    ],
    'projects' => [
        'Software' => [
            'CardioAI' => [
                'thumbnail' => '',
                'demo' => 'https://cardioai.org/',
                'gallery' => [
                    'video' => [],
                    'images' => [],
                    'pdf' => [],
                ],
            ],
            'SuiteHub' => [
                'thumbnail' => '',
                'demo' => 'https://suitehub.it/',
                'gallery' => [
                    'video' => [],
                    'images' => [],
                ],
            ],
            'ADMHub' => [
                'thumbnail' => '',
                'demo' => 'https://admhub.it/',
                'gallery' => [
                    'video' => [],
                    'images' => [],
                ],
            ],
        ],
        'Siti Web' => [
            'ChronoRealms' => [
                'thumbnail' => '',
                'demo' => 'https://choronorealms.it/',
                'gallery' => [
                    'video' => [],
                    'images' => [],
                ],
            ],
            'Ad Maiora' => [
                'thumbnail' => '',
                'demo' => 'https://admaiorasc.com/',
                'gallery' => [
                    'video' => [],
                    'images' => [],
                ],
            ],
            'FC Advisor' => [
                'thumbnail' => '',
                'demo' => 'https://fcadvisor.it/',
                'gallery' => [
                    'video' => [],
                    'images' => [],
                ],
            ],
            'Registra il Marchio' => [
                'thumbnail' => '',
                'demo' => 'https://www.registrailmarchio.it/',
                'gallery' => [
                    'video' => [],
                    'images' => [],
                ],
            ],
            'Solidarity Pass' => [
                'thumbnail' => '',
                'demo' => 'https://www.solidaritypass.org/',
            ],
            'Formentis' => [
                'thumbnail' => '',
                'demo' => 'https://www.formentis.it/',
            ],
        ],
        'App Native' => [
            'NPanel' => [
                'thumbnail' => '',
                'gallery' => [
                    'video' => [],
                    'images' => [],
                ],
            ],
            'Mira Store' => [
                'thumbnail' => '',
                'demo' => 'https://play.google.com/store/apps/details?id=it.mirastore.app&hl=it',
                'gallery' => [
                    'video' => [],
                    'images' => [],
                    'pdf' => [],
                ],
            ],
        ],
    ]
];
